// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3MoGwanlLEdGcXIm6FyX53MRtkeYkP80',
    appId: '1:548287487433:web:470fd6ab3b2b5c6e499c18',
    messagingSenderId: '548287487433',
    projectId: 'fir-flutter-codelab-28dce',
    authDomain: 'fir-flutter-codelab-28dce.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-28dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqgN2YLP_vGJG9LOL9jG96lG8Gvpn5Wko',
    appId: '1:548287487433:android:8102b80faf9a8531499c18',
    messagingSenderId: '548287487433',
    projectId: 'fir-flutter-codelab-28dce',
    storageBucket: 'fir-flutter-codelab-28dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtE90Dh2jIfV5QtBytguUL9s3CfBry_w',
    appId: '1:548287487433:ios:13349b516359ef6c499c18',
    messagingSenderId: '548287487433',
    projectId: 'fir-flutter-codelab-28dce',
    storageBucket: 'fir-flutter-codelab-28dce.appspot.com',
    iosClientId: '548287487433-13eg8nt42o1n6eag2d1oouttt1cjf23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAtE90Dh2jIfV5QtBytguUL9s3CfBry_w',
    appId: '1:548287487433:ios:13349b516359ef6c499c18',
    messagingSenderId: '548287487433',
    projectId: 'fir-flutter-codelab-28dce',
    storageBucket: 'fir-flutter-codelab-28dce.appspot.com',
    iosClientId: '548287487433-13eg8nt42o1n6eag2d1oouttt1cjf23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
